### PR TITLE
[JENKINS-33808] Support for Item categorization

### PR DESCRIPTION
**Pull request by recena**
[JENKINS-33808](https://issues.jenkins-ci.org/browse/JENKINS-33808)

downstream of https://github.com/jenkinsci/scm-api-plugin/pull/9

@reviewbybees especially @jglick

### Screenshot

jenkins-33808

### CODE REVIEW

**Comment by amuniz** [comment]
Changes look good. Retriggering the build.

**Comment by amuniz** [comment]
Tests running fine locally, let's get this merged and I will investigate the test timeout separately :bee:

**Comment by amuniz** [comment]
Not merging until `scm-api:1.2-SNAPSHOT` is released.

**Comment by jglick** [comment]
:bee:

**Comment by recena** [comment]
@amuniz `scm-api-1.2` released and dependency upgraded.

**Comment by yoss329** [comment]
Screenshot_20250529-002147
[](url)c1ac2301f92bbebc0b4c3352048b5dd0f8d3ed0f

**Pull request merged**
