### PR TITLE
Issue #188: Calling teams API without auth

### PR DESCRIPTION
**Pull request by ieugen**
### Your checklist for this pull request

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!

- [x] Please describe what you did

- [x] Link to relevant GitHub issues or pull requests

- [ ] Link to relevant [Jenkins JIRA issues](https://issues.jenkins-ci.org)

- [ ] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### Description

This is exploratory code. Not a complete fix. The logging part is most useful 

I've added some logging and improved debugging for #188 .
I've also fixed the API call to get teams so that it does not require Auth - this works for the teams API.
Sending Basic auth makes the call fail with http 401 .

The fix does not completely resolve the issue. Listing the repositories requires some changes as well.

### CODE REVIEW

**Comment by casz** [comment]
@ieugen instead of logging, you can use `mvn hpi:run` in your IDE, the debugger will be attached.

**Comment by ieugen** [comment]
Thanks I did not know that. I'm running Jenkins remotely, I don't normally do Jenkins devel. I imagine it doesn't work in that case.

**Comment by sheona-harry** [comment]
Hi! Why hasn't this been merged yet?

**Comment by casz** [comment]
@ieugen do you have the intention to finish this? 😅

**Comment by ieugen** [comment]
Hi @casz, I don't have time to address this at the moment.

**Pull request closed without merging**
