### PR TITLE
Enable plugin to pull sync submodules (if present)

### PR DESCRIPTION
**Pull request by joeabbey**
FYI: I've included a Jenkinsfile in this PR, so please don't feel compelled to pull it.

The bulk of the changes for this PR are in BitbucketSCMSource.java.  A SubmoduleOption with some relatively sane default values is instantiated and then passed to the GitSCM constructor.  This enables any repo with submodules (even recursive ones) to automatically sync the submodules on checkout during pipeline execution.

I'm not super excited that submodules are enabled by default.  On the other hand, now that the jenkins git plugin has released 3.0.0, I think its a good time to start evaluating this approach.  I would prefer to see this as a "Property Strategy" to incorporate in a multibranch pipeline job configuration.

### CODE REVIEW

**Comment by amuniz** [comment]
I'm 👎 on adding this opinionated option by default (without a way to disable it).

Moreover, the submodule sync can be done just after `checkout scm` by using a `sh` step and `git submodule ...`

**Comment by joeabbey** [comment]
@amuniz I thought that too... which is what I originally tried to do but the underlying gitscm client pulls the credentials as it tears down.   When I've tried to run any subsequent commands ( on ephemeral nodes ) the git operations fail to authenticate...   (yes I could inject the SSH keys.. but I've already specified them in the bitbucket branch plugin

I've looked through the webapp stuff and I think adding a "sync submodules" checkbox should be doable.  Would that address your desire to make it optional?

**Comment by amuniz** [comment]
> Would that address your desire to make it optional?

You are right, and your thoughts made me think that I'm against this feature at all (even being optional). I mean, repository specific configuration in the branch source must serve one and only one purpose: retrieve info from the WS API and checkout sources as a plain `git/hq clone` would do. Other than that would be to couple the implementation to a concrete SCM and open a door for other _specific_ configurations, which eventually would lead to a full copy of the general Git/Mercurial plugin configuration.

There is another way to achieve what you want: modify the `scm` object configuration at runtime (before running `checkout scm`. Something like 

```
import hudson.plugins.git.extensions.impl.SubmoduleOption
scm.extensions.replace(new SubmoduleOption(false, true, false, "", 10000, true))
checkout scm
```

Would that work for you?

**Comment by kjwise** [comment]
Just noting that I've spent the day battling this at my place of work. The Git plugin has an option to add additional behaviors to the SCM multibranch configuration but this plugin does not show that (see: https://support.cloudbees.com/hc/en-us/articles/226122247-How-to-Customize-Checkout-for-Pipeline-Multibranch)

I would expect having the same configuration available regardless of BitBucket or Git being the underlying plugin. Still, I'll try the workaround you posted 40 minutes ago.

**Pull request closed without merging**
