### PR TITLE
[JENKINS-47124] - change getBranches method to use Bitbucket API 2.0

### PR DESCRIPTION
**Pull request by YevgeniyShpolyanskiy**
Fix bug which doesn't allow get more than ~100 branches from Bitbucket repository, because 1.0 Bitbucket API doesn't support pagination which added in 2.0 Bitbucket API

### CODE REVIEW

**Comment by DmitriyStoyanov** [comment]
Thanks, it works!

**Comment by casz** [comment]
Jenkins azure repo has been seeing a few issues lately. Failing to retrieving all dependencies.

**Comment by YevgeniyShpolyanskiy** [comment]
@casz , thanks, got it :)

**Comment by YevgeniyShpolyanskiy** [comment]
@casz , could you please give me a piece of advice how to retrigger CI build of this pull-request?

**Comment by casz** [comment]
Empty commit or open and close pr

**Comment by casz** [comment]
I guess this can be closed now, that it is already taken care of by #73

**Comment by amuniz** [comment]
This PR is superseded by #73

**Pull request closed without merging**
