### PR TITLE
Cleanup deprecated code

### PR DESCRIPTION
**Pull request by nfalco79**

### CODE REVIEW

**Comment by basil** [comment]
@nfalco79 Breaks downstream test `io.jenkins.blueocean.blueocean_bitbucket_pipeline.cloud.BbCloudPipelineCreateRequestTest#createPipeline` with

```
[ERROR] io.jenkins.blueocean.blueocean_bitbucket_pipeline.cloud.BbCloudPipelineCreateRequestTest.createPipeline -- Time elapsed: 12.44 s <<< FAILURE!
com.github.tomakehurst.wiremock.client.VerificationException: 
3 requests were unmatched by any stub mapping. Shown with closest stub mappings:
 expected:<
GET
/rest/api/1.0/projects/vivektestteam/repos/pipeline-demo-test
> but was:<
GET
/rest/api/1.0/projects/vivektestteam/repos/pipeline-demo-test/branches?start=0&limit=200
>

 expected:<
GET
/rest/api/1.0/projects/%7B47cd7cf2-ca31-4c90-bc0e-4c7ef67f9dfe%7D/repos/pipeline-demo-test
> but was:<
GET
/rest/api/1.0/projects/vivektestteam/repos/pipeline-demo-test/branches?start=0&limit=200
>

 expected:<
GET
/api/2.0/repositories/%7B47cd7cf2-ca31-4c90-bc0e-4c7ef67f9dfe%7D?page=1&limit=100
> but was:<
GET
/rest/api/1.0/projects/vivektestteam/repos/pipeline-demo-test/branches?start=0&limit=200
>
        at com.github.tomakehurst.wiremock.client.VerificationException.forUnmatchedNearMisses(VerificationException.java:55)
        at com.github.tomakehurst.wiremock.WireMockServer.checkForUnmatchedRequests(WireMockServer.java:545)
        at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:70)
        at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:706)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

The problem can be reproduced on an AMD64 system by cloning the Blue Ocean Git repository, then applying

```xml
diff --git a/blueocean-bitbucket-pipeline/pom.xml b/blueocean-bitbucket-pipeline/pom.xml
index 0b2cae80c..8fdbb30ce 100644
--- a/blueocean-bitbucket-pipeline/pom.xml
+++ b/blueocean-bitbucket-pipeline/pom.xml
@@ -26,6 +26,7 @@
     <dependency>
       <groupId>org.jenkins-ci.plugins</groupId>
       <artifactId>cloudbees-bitbucket-branch-source</artifactId>
+      <version>906.vedf430cb_4481</version>
       <exclusions>
         <!-- Upper bound fix: later version of jsch is picked from git-plugin's transitive dependency -->
         <exclusion>
diff --git a/pom.xml b/pom.xml
index 9395690e4..ca42cd558 100644
--- a/pom.xml
+++ b/pom.xml
@@ -32,7 +32,7 @@
         when changing jenkins core version please remember to change it in Jenkinsfile as well jenkinsVersions
         and  acceptance-tests/runner/scripts/args.sh
     -->
-    <jenkins.version>2.426.3</jenkins.version>
+    <jenkins.version>2.462.3</jenkins.version>
     <javadoc.exec.goal>javadoc-no-fork</javadoc.exec.goal> <!-- stop initialize phase plugins executing twice -->
     <byte-buddy.version>1.14.9</byte-buddy.version>
     <node.version>10.13.0</node.version>
@@ -219,8 +219,8 @@
 
         <dependency>
             <groupId>io.jenkins.tools.bom</groupId>
-            <artifactId>bom-2.426.x</artifactId>
-            <version>2961.v1f472390972e</version>
+            <artifactId>bom-2.462.x</artifactId>
+            <version>3221.ve8f7b_fdd149d</version>
             <scope>import</scope>
             <type>pom</type>
         </dependency>
```

and running

```
mvn clean verify -Dtest=io.jenkins.blueocean.blueocean_bitbucket_pipeline.cloud.BbCloudPipelineCreateRequestTest#createPipeline -Dspotbugs.skip -Dspotless.skip -Denforcer.skip -Daccess-modifier-checker.skip -Dcheckstyle.skip -Dskip.npm
```

As a result of this new test failure, we have rolled back the upgrade of Bitbucket Branch Source from 906.vedf430cb_4481 back down to 895.v15dc41668f03 in https://github.com/jenkinsci/bom/pull/3919.

When the new test failure is fixed in Blue Ocean and when that fix is released in a new version of Blue Ocean, then we will upgrade Bitbucket Branch Source from 895.v15dc41668f03 to 906.vedf430cb_4481 in `jenkinsci/bom`.

**Comment by darxriggs** [comment]
With this change in Jenkins under `Manage Old Data` there are `CannotResolveClassException: repositoryType` entries that have to be cleaned up.

**Comment by darxriggs** [comment]
In this repository in the test data there are also a lot of XML files that still contain `<repositoryType>GIT</repositoryType>`.

**Comment by sebastienmascha** [comment]
Thanks @MarkEWaite and @darxriggs. Indeed, I faced both issues:
- CannotResolveClassException: repositoryType
- CannotResolveClassException: com.cloudbees.jenkins.plugins.bitbucket.MergeWithGitSCMExtension

It is easy to fix manually by removing the line for repositoryType.

For the second error (MergeWithGitSCMExtension), it does not break my pipeline. I am able to run an old build and it will automatically replace: `com.cloudbees.jenkins.plugins.bitbucket.MergeWithGitSCMExtension` by `jenkins.plugins.bitbucket.MergeWithGitSCMExtension`

For a classic multi-branch build trigger by a Bitbucket webhook on branches and PR, should I use something different than `jenkins.plugins.bitbucket.MergeWithGitSCMExtension`?

**Comment by nfalco79** [comment]
Let me try with these changes:
```
    @Initializer(before = InitMilestone.PLUGINS_STARTED)
    public static void aliases() {
        Items.XSTREAM2.addCompatibilityAlias("com.cloudbees.jenkins.plugins.bitbucket.MergeWithGitSCMExtension", MergeWithGitSCMExtension.class);
    }
```

**Comment by nfalco79** [comment]
> With this change in Jenkins under `Manage Old Data` there are `CannotResolveClassException: repositoryType` entries that have to be cleaned up.

That transient field has been removed since it was not used. It's sage ignore or discard those data.
See also issue https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/907

**Comment by nfalco79** [comment]
@basil 
I check the issue for blue ocean plugin, I miss to setup the primary clone links before build the SCM source.
I had test with an incremental build as mention in the comment above.
Follow specific PR for this.

**Pull request merged**
