### PR TITLE
Added a simple sleep and retry loop when rate limiting occurs

### PR DESCRIPTION
**Pull request by melvyndekort**
An Atlassian team member explains that there currently is no way to predict when rate limiting will occur on this page: https://community.atlassian.com/t5/Answers-Developer-Questions/Finding-out-request-left-until-I-hit-the-API-rate-limit/qaq-p/549595

Therefore I've created a simple fix in the `BitbucketCloudApiClient.getRequest(...)` which does a sleep and a retry when status code `429` is returned.

### CODE REVIEW

**Comment by michaelneale** [comment]
LGTM - @vivek @stephenc I have done almost the same thing before, works a treat. Any reason we can't merge this in (ie is that a bad place to have a sleep, is all I can think).

**Comment by stephenc** [comment]
> ie is that a bad place to have a sleep, is all I can think

nope, exactly the right place to sleep - as long as InterruptedException is propagated (it is) - this is the analogous sleep as in the GHBS

**Comment by stephenc** [comment]
@michaelneale I'll leave it up to @vivek / @abayer / @svanort / @amuniz to cut a release (unless I have a dire need for a release first - unlikely)

**Comment by michaelneale** [comment]
Thank you @Stephenc yes we may time a release with a possible fix for light weight cloning. 🙏

**Pull request merged**
