### PR TITLE
Update parent pom, update jenkins core, use bom

### PR DESCRIPTION
**Pull request by casz**
### Your checklist for this pull request

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

**Comment by casz** [comment]
@amuniz @stephenc I would appreciate if you could have a look at the test failures.

I am not even sure why this is failing but it seems to be related to the mocking/spying.
https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fbitbucket-branch-source-plugin/detail/PR-238/1/tests

In a live instance everything is working.

**Comment by amuniz** [comment]
Failure in indexing logs is:
```

**Comment by stephenc** [comment]
I have given up on mocks for testing these kinds of things

**Comment by amuniz** [comment]
I think I found the problem.
This is fixing the issue:
```
diff --git a/src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BranchScanningIntegrationTest.java b/src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BranchScanningIntegrationTest.java
index b365a78..95afab8 100644
--- a/src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BranchScanningIntegrationTest.java
+++ b/src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BranchScanningIntegrationTest.java
@@ -191,13 +191,9 @@ public class BranchScanningIntegrationTest {
 
             @Override
             public FreeStyleProject newInstance(Branch branch) {
-                FreeStyleProject job = new FreeStyleProject(getOwner(), branch.getName());
-                job.onCreatedFromScratch();
-                FreeStyleProject spied = spy(job);
-                // Do nothing.. Running the actual build is not desired/required (and not possible) in this tests.
-                when(spied.scheduleBuild()).thenReturn(false);
-                setBranch(spied, branch);
-                return spied;
+                FreeStyleProject job = new FreeStyleProject(getOwner(), branch.getEncodedName());
+                setBranch(job, branch);
+                return job;
             }
 
             @Override
```

That spying on the job was causing problems, and is not needed anymore, I believe.

**Comment by casz** [comment]
fixed two of them. Down to one test which is also doing some odd mocking 😓

**Comment by casz** [comment]
Not sure what changed in mocktio 3 that does not allow calling real method on a subclass when call is done on super

**Pull request merged**
