### PR TITLE
Feature/include all prs

### PR DESCRIPTION
**Pull request by osbornk**
We need this to include feature branches as well as all pull requests. So, we have the following pattern.

Branch includes: /feature/*/master /release/*

But we also want to build all pull requests. So a new checkbox for "Include all pull requests" was added.

We did this pattern because we were finding that when we pushed a commit to a branch that had an associated pull request, Jenkins was building twice. Once for the pull request and another for the branch associated with that pull request. That was putting a lot of strain on our Jenkins.

I also fixed the pattern notation to allow a wildcard in any position, not just the beginning or end.

### CODE REVIEW

**Comment by tknerr** [comment]
see also #9

**Comment by stephenc** [comment]
All UI changes are being blocked until I complete the parity UI config with the new UI config I am implementing to be shared by Bitbucket and GitHub. Here is the GitHub preview

jenkins-43507

**Comment by bhipple** [comment]
Any progress on this one?  I'm running into the [include branches bug](https://issues.jenkins-ci.org/browse/JENKINS-36890) and would like to have this if possible.

**Comment by stephenc** [comment]
Will be considered *after* the combined GitHub/Bitbucket UI refactoring to use common shared behaviours (and may even be fixed by that refactoring)

**Comment by stephenc** [comment]
likely superseded by #53

**Pull request closed without merging**
