### PR TITLE
update Jackson

### PR DESCRIPTION
**Pull request by casz**
cleaned up unused imports as well

### CODE REVIEW

**Comment by nfalco79** [comment]
I remember a discussion with @jglick on google group about the use of plugin API to share common libraries like jackson to avoid duplication of the same jar (maybe also with different version) and classloader issues.

So I was expecting a dependency like
```
    <dependency>
      <groupId>org.jenkins-ci.plugins</groupId>
      <artifactId>jackson2-api</artifactId>
      <version>2.8.11.3</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-annotations</artifactId>
      <version>2.8.11</version>
    </dependency>
```
That means also move project to java 8 due to `Restricted to JDK 1.7 yet com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.8.11:compile contains com/fasterxml/jackson/datatype/jsr310/DecimalUtils.class targeted to JDK 1.8`

Reported here for public visibility

**Comment by casz** [comment]
Yes you are absolutey correct, I should remembered to use the jackson2 api plugin 😅

Also should have left the PR open to get input before merging, it seemed safe at the time I was not getting a restricted warning when compiling it 😢

**Comment by nfalco79** [comment]
I looking why the jackson-annotations seems to be needed also if seems a transitive dependencies of one of the dependency of jackson 2 api plugin.

**Comment by casz** [comment]
The test you have in #139 fails with jackson-api-plugin 2.7.3 which is the mimimum version for java 7 also fails with jackson-api-plugin 2.8.11.2

**Comment by nfalco79** [comment]
ok I got the point

**Comment by nfalco79** [comment]
Which version you will plan to use? 2.7.3 to be compatible with actual java 7 version?

**Comment by casz** [comment]
I kinda want version 2.9 of jackson since it fixes your date format issue 😅

**Comment by casz** [comment]
I will probably end up reverting, the jackson changes make a release then reintroduce the jackson update.

**Comment by nfalco79** [comment]
me too, I could use the deprecated ISO8061DateFormat untill (after open an issue to jackson2-api) update jackson to 2.9.2 (at least)

**Comment by casz** [comment]
created https://github.com/jenkinsci/jackson2-api-plugin/pull/10 which has a incremental artifact: https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/jackson2-api/2.9.6.0-rc68.646ed7808a55/

**Pull request merged**
