### PR TITLE
Incrementals

### PR DESCRIPTION
**Pull request by casz**
Support for incremental would be nice for this repo, to speed up the deployment of PRs for extension plugins! Please consider merging 👍 
See [JEP-305 for context](https://github.com/jenkinsci/jep/blob/master/jep/305/README.adoc)

### CODE REVIEW

**Comment by casz** [comment]
Hopefully this should simplify deployment of #127 once this PR is merged

**Comment by michelzanini** [comment]
Would be good to merge this together once #127 is merged 👍

**Comment by coltrey** [comment]
@amuniz Do you think you can merge this and #130 prior to cutting a new release?  This will enable @michelzanini to create an attribute plugin for project filtering in bitbucket cloud - a feature several folks have been waiting eagerly for.

**Comment by michelzanini** [comment]
Thanks @coltrey ,

I do not need #130 to be merged for the filter project plugin, but I need this PR or a new release of Bitbucket Branch Source.

On #130 there is still a small issue I need help with before merging.

Thanks.

**Comment by casz** [comment]
@coltrey enabling incrementals for this repo does not require a release
What it does allow for, is that https://ci.jenkins.io/ will upload an artifact of the all future PR commits which allows other developers to develop new features faster where they might depend on this plugin.

**Pull request merged**
