### PR TITLE
Revert "Merge pull request #147 from Nuglif/fix_notification"

### PR DESCRIPTION
**Pull request by casz**
This reverts commit 359a60f9ffb066925f4ad95c5d2fe6db6ab47b7c.

### CODE REVIEW

**Comment by casz** [comment]
Based on @jeubank12 comment: https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/147#issuecomment-433990123
> > Also, Since the «Branch Job» is disable there is no point to keep the BuildStatus history in Bitbucket.
> 
> This is only true if you "Exclude branches that are also filed as PRs". Now merge checks in Bitbucket fail because only one build has been reported instead of the two that existed prior to this fix
> 
> image
> 
> Would request that this issue is reverted in favor of a solution which checks whether the PR source job has been disabled

I am inclined to revert your change @pascallap

**Comment by henrikb123** [comment]
I strongly believe it was a bad idea to revert this very desirable fix.

The comment about failing merge checks is based on having the Bitbucket repository setup to expect more than one successful build from the same job on the same commit (one on the branch, one on the pull-request). This is a bad setup that could/should simply be changed to expect one build for a job/commit combination; the natural relationship here is job-name/commit-id. **The valid case for wanting to see multiple builds on a Bitbucket commit is when there are several jobs doing differing tasks** (e.g. one for build, one for integration tests etc.). Seeing multiple builds for the same commit and the same job breaks stuff as exemplified below.

_An example ("Exclude branches that..." setting has no relevance here but let's say it's active):_
Someone creates a pull-request for a branch with HEAD abc1234. The build fails for reasons outside control of the content of the branch/PR (e.g a database was unaccessible during the build). It's regarded as a bad time to process this change and the PR is deleted. Later a new PR is created on the same HEAD abc1234. The triggered build is successful. BUT with the current code, Bitbucket will show two builds - one success and one failure from the deleted PR. There's now no way to get rid of the failing build with less than doing funky admin stuff involving REST calls to fake success of the first job.

**A job with the same job-name/commit-id combination as a previous one should ALWAYS override the previous result.**

**Comment by wouterhund** [comment]
@henrikb123 This change broke this plugin for us. Reverting it is a very good idea, and in the future such breaking changes should be put in a major version bump, or configurable.

We are building both branches and PRs. Both builds are subtly different, and both need to report their status to bitbucket. On bitbucket we are only allowed to merge PRs if both builds succeeded. Suddenly, Jenkins is only reporting the status of one build.

This is an unexpected breaking change, and also makes no sense. They're separate builds. Both builds ran and reported, but for some reason only the latest one is being shown now.

You call this a bad setup, but you don't explain why. I assume you are aware that the result of a merge is different from the original commit? Having builds for both lets you see test results of both cases, which can be very informative.

If this feature is going to be added, it absolutely has to be configurable and not the default.

**Comment by casz** [comment]
I agree @wouterhund, I guess I did not think through all the cases with traits.
This would be another good trait as well I guess.

**Comment by henrikb123** [comment]
I'd take configurable, that would be great. I also agree this was a breaking change that also caused headache for me. 

@wouterhund 
Just to explain the "bad setup" statement.
I mean Bitbucket should be setup to expect the number of builds equal to the unique Jenkins job(s) it triggers.

Having the same commit built by the same job twice provides no additional information in any setup I have seen. In what way are your PR builds and branch builds subtly different? Just so that I can understand your use-case.


I know the result of a merge is different than the original commit (unless you rebase and do an fast-forward merge), but I also know the result will be a merge commit with its own id, hence I don't see the relevance - the Jenkins build result will then be attached to THAT commit in Bitbucket post merge.

**Comment by jeubank12** [comment]
When Jenkins does a merge prior to building a PR, it does not push it to Bitbucket. It notifies the source commit of the build status.

**Comment by casz** [comment]
@henrikb123 @wouterhund @jeubank12 as a hint you can follow the project to stay up to date with PRs 😅

image

**Comment by wouterhund** [comment]
@casz Done ;)

@henrikb123 One somewhat common case is when you write a unit test in a branch, and that branch isn't up to date with master. It will merge cleanly with master, but the test assumes certain behavior that got changed in master. Now the test will fail after merge, and the code may not function as intended. And it's nice to see the difference between pre-merge and post-merge, rather than just the post-merge result.

Of course if developers kept their branches up to date prior to creating PRs, that'd work. But we have CI so we don't need to think about this stuff too much.

**Comment by henrikb123** [comment]
@casz 
Now a follower :)

@jeubank12 
I'm fully aware. I thought we were discussing merging in general, not at Jenkins build time. This was before the use-case was explained.

@wouterhund 
Then I understand how you use it - the fact that the user can hang around on the comfortable branch state where no conflicts exists ;)

Having the plugin setup to build all branches even if a PR exists, I realize you need build status from both, otherwise someone could cheat Bitbucket to allow merge by overriding the build result with a build from the branch that will later fail post (actual) merge.

As you can see the current behaviour provides no benefits when having "Exclude branches..." setting and personally I prefer this because I think result with current state of master is the one that matters, but this is a matter of taste. Instead there's a disadvantage that I described in my first post which will happen in a big organization and will require admin intervention every time.

Thus, I'm hoping for configurability for this behaviour.

**Comment by casz** [comment]
Funny how a one line change can bring to much discussion 🤭 quite awesome, actually 🙌

**Comment by pascallap** [comment]
The real problem that we were facing was:
If you commit on a branch and quickly generate a Pull Request you will end up with 2 jobs (branch and PR) running at the same time.
We have implemented an abort a running Branch Job matching for a running PR within the pipeline. So we were always sending a failure build result for the Branch Job.

There is probably 2 distincts traits needed:
 - Abort running Branch Job if a PR is running (without failure notification to BitBucket)
 - Override BitBucket BuildStatus history for a single BuildStatus.

**Comment by tarioch** [comment]
Was reading through the release notes of 2.2.13 and really happy with the change, finally getting rid of the duplicate and wrong stati which is a problem as it makes the build status in bitbucket useless if there was an infrastructure issue when a job started on the branch before the pr was created.
Is there any plan to redo this? Maybe just make it a trait?

**Pull request merged**
