### PR TITLE
Jenkins 40958 - Allow pullrequest approved in webhooks for bitbucket multibranch projects

### PR DESCRIPTION
**Pull request by kylec32**
I have a use case where I need to wait until a pull request has been approved before kicking off a build and I noticed this improvement was logged as JENKINS-40958 so I figured I would offer my change. Simply added it as a recognized request type and from that point it gets treated as an update request and successfully kicks off the build.

### CODE REVIEW

**Comment by ApacheEx** [comment]
+1, looks good.

**Comment by stephenc** [comment]
This would need to be implemented as a `SCMSourceTrait` that basically filters pull requests until the pull request itself has entered the approved state

**Comment by stephenc** [comment]
We should revisit once #53 is merged

**Comment by stephenc** [comment]
Unclear how this works (other than potentially consuming more API calls)

If you have an extension plugin adding an `SCMTrait` that is filtering PRs until they are approved, then this is fine to merge once rebased...

If you don't have such an extension plugin then this change could have a negative impact on other users w.r.t. API rate limits and thus we would need to make the listening for this event opt-in

**Comment by shmish111** [comment]
@stephenc can you explain the rate limits a little? I also need this, I had a pull request open a long time ago but it was superseded by something and now both PRs seem to have disappeared? I'm currently stuck using a fork of a very old version of this plugin but I don't really want to for again and add a change that will not be merged eventually. It seems very important that a webhook is called when a pull request is approved, I think a lot of people will use a similar workflow in that they don't want to build until approval occurs. Personally I need to build both before and after approval which also requires me to hack the Jenkins plugin because that won't build if the sha of the PR hasn't changed, but I can live with that, it makes sense that for most people it wouldn't be good to build again if the sha remains the same.

Either way, I see this hook as pretty important to a lot of people.

**Comment by stephenc** [comment]
@shmish111

Every API call consumes a rate limit that Bitbucket Cloud provides of X number of API calls per hour.

To implement this feature, basically every PR would need to be checked any time there is a scan / event received. The check will add another API call for every PR.

There will be users who do not want this feature and users who do. The users who do not want the feature should not have to pay an additional API call per PR.

Additionally, the principle we are following is to keep the core plugin functionality minimal and allow various flavours of behaviour to be added by "SCMTrait" (which shows up in the UI as additional behaviours)

The policy here is to close PRs where the functionality should be implemented in an extension plugin. There will be cases where implementing an extension plugin will require additional extension points in the core plugin... in those cases PRs against the core plugin are welcome... as are bug fixes.

If a PR is adding a UI element, most likely it should be implemented as an extension plugin.

In any case, I am unclear as to exactly how this PR works for the requirement and my query is will it burn up API calls faster, and if so, is there some way we can prevent that for users who do not need it

**Comment by shmish111** [comment]
ok, I see, so if a pull request approved event is received, it is not possible to just look at that pull request? Instead all pull requests are queried again?

Does it seem like an extension plugin would be able to force building of a pull request when it has been approved but the git sha has not changed? It seems unlikely if the core functionality works by looking at all the PRs and seeing what has changed I guess this would not be possible?

**Comment by kylec32** [comment]
@stephenc I actually have started working on this again in the last few days going the `SCMTrait` route. I think with what I currently have implemented there could be potential increased API usage in that Approval webhook requests are respected and cause processing to happen. However if they don't have "Needs approval" turned on (via the `SCMTrait`) then no additional API calls will be made when processing. I don't know if this gets rid of the worry or not but just some additional information. 

If I'm understanding your above comments correctly a PR to this repo adding the "RequireApproval" SCMTrait will likely not be approved since this isn't "core" and adds more UI?  If that is the case it does make me a little sad as this is a fairly common use case I would say and shouldn't add much at all to the plugin. Trying to think through how my changes would even be pulled out into a different plugin I'm not sure since it's filtering out PRs right from the heart of the `retrievePullRequests` function in `BitbucketSCMSource.java`. Is there an example of an extension plugin that you know of that does similar things so maybe I can look at that and get a better understanding of how it would work?

**Comment by casz** [comment]
@kylec32 the extension you created will need to be moved into an extension plugin if you made your extension correctly the plugin will be adding the extra UI and if you want the plugin to be exposed to other instances you should have it hosted at Jenkins org on GitHub.

See these plugins as examples, there is a GitHub link on that page:
https://plugins.jenkins.io/bitbucket-scm-filter-jira-validator
https://plugins.jenkins.io/bitbucket-scm-filter-aged-refs
https://plugins.jenkins.io/bitbucket-scm-trait-commit-skip

**Comment by kylec32** [comment]
Closing this in favor of PR #107

**Pull request closed without merging**
