### PR TITLE
[JENKINS-34071] Added the possiblity to filter using the Bitbucket Cloud project name

### PR DESCRIPTION
**Pull request by saiimons**
I added the possibility to match the Bitbucket Cloud project when scanning repositories.

Although, "project" seems to be used differently on Bitbucket Server, and I don't have any experience with it, I am not sure the implementation will be working correctly.

### CODE REVIEW

**Comment by saiimons** [comment]
Not quite sure why the build failed, especially as I did not change anything in the pom.xml

**Comment by saiimons** [comment]
Found out I forgot to push some changes and I have to fix some test cases...

**Comment by amuniz** [comment]
This needs further investigation because I'd like to have a UI as isolated as possible from BB Server or Cloud, and currently BB Cloud is offering 3 levels of indirection (team, project and repo) while BB Server only offers 2 (project and repo).

**Comment by Tomschi** [comment]
It is an useful Feature and we would need it in our company. Is there any time schedule to finish this feature?

**Comment by stephenc** [comment]
It should be possible to implement this as a `SCMNavigatorTrait` that adds a `SCMSourceFilter` or a `SCMSourcePrefilter` to the `BitbucketSCMNavigatorContext` in a bb-server specific plugin that depends on this generic plugin once #53 is merged. If there are issues with that (say the `BitbucketSCMNavigatorRequest` does not provide the relevant information) then those specific changes are relevant in this plugin

**Comment by chrisburrell** [comment]
Any chance this could be merged in? We're ve got around hundred repos and so being able to categorise by project would make a massive difference!

**Comment by stephenc** [comment]
Needs to be reworked to use traits. Perhaps can even be reasonably trivially implemented as an extension plugin - if you do not care about API rate limits a [SCMSourceFilter](https://github.com/jenkinsci/scm-api-plugin/blob/0ad53b1a93ec796258423d39254c9edae27837d7/src/main/java/jenkins/scm/api/trait/SCMSourceFilter.java#L50) can retrieve the team for each project and exclude as desired, would be a relatively simple implementation.

If you care about rate limits then we would need to augment [BitbucketSCMNavigatorRequest](https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/cloudbees-bitbucket-branch-source-2.2.0-alpha-1/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigatorRequest.java) to provide the `BitbucketRepository` instances so that you could make decisions in filters without having an additional network round trip.

In either case the `SCMNavigatorTrait` implementation would just add the filter to the request and the rest should JustWork™

**Comment by tgeens** [comment]
@saiimons @stephenc Now that PR #53 is merged - can we pick up this again ?

Looking at the last comment of @stephenc it sounds like this needs a different approach ?

**Comment by saiimons** [comment]
@tgeens I have a lot on my plate right now, but I'll give a hand as soon as I get enough free time ;)

**Comment by chrisburrell** [comment]
This feature would be really helpful as it would restrict what gets scanned and make the whole process of finding new repositories faster. It would also allow us to segregate different teams/projects with their set of repos. Any ideas on whether anyone is working on this? At the moment we have one team within Bitbucket and so we have in the order of 60-70 repositories scanning all the time, so it takes quite a while.

**Comment by michelzanini** [comment]
I have re-done this PR using traits, please look at the PR at https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/127

**Comment by nfalco79** [comment]
Than please author or any other with permission close this PR to avoid growing of PR and focus attention to where is needed.

**Comment by casz** [comment]
Superseeded by #127

**Comment by michelzanini** [comment]
@saiimons , @chrisburrell , Tomschi this plugin is now released and available here:
https://plugins.jenkins.io/bitbucket-filter-project-trait

**Comment by Tomschi** [comment]
@michelzanini Thank you very much!

**Pull request closed without merging**
