### PR TITLE
[JENKINS-55068] Only consider 404 as path does not exist

### PR DESCRIPTION
**Pull request by tarioch**
Otherwise throw an IOException, fixes #JENKINS-55068

### CODE REVIEW

**Comment by vivek** [comment]
@tarioch LGTM! Thanks for submitting PR to fix it.

**Comment by tarioch** [comment]
Just to confirm that this indeed fixes our issues. The scanning log now shows the exception and does not drop the jobs anymore.

**Comment by vivek** [comment]
@rsandell Please release bitbucket-branch-source plugin with this fix. It's been hurting other users, https://issues.jenkins-ci.org/browse/JENKINS-55220 is possible due to the same issue.

**Comment by casz** [comment]
@vivek done 😅 should appear in the update center in a few hours.

**Comment by vivek** [comment]
Awesome, thanks @casz 🎉

**Pull request merged**
