### PR TITLE
Use unified build status key with exclude origin PR Branches strategy

### PR DESCRIPTION
**Pull request by JeanChristopheMorinPerso**
…r filter is used.

Little improvement in the way the build status key is named when the `Discover branch` option is set to `Exclude branches that are also filed as PRs`. With these changes, the build key for a branch that then goes into PR will stay the same (`<project_name>/<branch_name>`), like it is for any branch right now.

I tested all possible options of the discover branch and my change is really only affecting the build key when `Exclude branches that are also filed as PRs` is chosen.

This should hopefully fix https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/160. I also hope it will be more solid than https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/147.

I'm not a Java developer, and so I did my best with the knowledge I have to keep the code style. Let me know if there is anything to change.

### CODE REVIEW

**Comment by casz** [comment]
@JeanChristopheMorinPerso I think it would be better to just pass the bitbucketsource that is already defined in `sendNotifications` method and pass to `createStatus`

**Comment by casz** [comment]
I have gone ahead and added my suggestion, please feel free to review it :)

**Comment by JeanChristopheMorinPerso** [comment]
Thanks a lot @casz , it looks much nicer now. I'll test the changes later today (even if not much change from my changes). I really appreciate the time you took to improve the PR! :)

**Comment by JeanChristopheMorinPerso** [comment]
I'll fix the build. Looks like one import is wrongly ordered.

**Comment by casz** [comment]
@JeanChristopheMorinPerso fixed :+1:

**Comment by JeanChristopheMorinPerso** [comment]
Looks like you are faster than me :smile: Tested the latest changes and everything looks good :+1:

**Comment by JeanChristopheMorinPerso** [comment]
@casz Do you a time frame for when the next release will happen? Don't want to be pushy or anything... It's more by curiosity.

**Comment by casz** [comment]
Would be great if I could land this and #174 together in next release :smile:

**Comment by casz** [comment]
I'll see if I can land the PRs myself in the weekend

**Comment by JeanChristopheMorinPerso** [comment]
Thanks!

**Comment by timshadel** [comment]
@casz Any update on getting this PR in and released? It'd really help us out! 😄

**Comment by casz** [comment]
Time did not allow me to work on this :|
Since the authors PR of #173 and #174 is not willing to listen to PR reviews, I have to do the work myself.

**Comment by JeanChristopheMorinPerso** [comment]
Thank you @casz ! I really appreciate the time you took to improve the work I initially did on this PR :)

I'm sure a lot of other people will be happy to see this feature finally released.

**Pull request merged**
