### PR TITLE
[JENKINS-65719] Only retrieve the PR when fetching a PR head revision

### PR DESCRIPTION
**Pull request by Dohbedoh**
[JENKINS-65719](https://issues.jenkins.io/browse/JENKINS-65719) Only retrieve the PR we are interested when retrieving a PR Head revision.

### Your checklist for this pull request

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

**Comment by Dohbedoh** [comment]
Tested against a Bitbucket Server 7, with a Multibranch Pipeline for different kind of scenario: PR Head with or without conflicts, PR Merge (no lightweight checkout so does not matter here), PR Head from forks, even branches to make sure that does not break anything.

**Comment by Dohbedoh** [comment]
WIP: Still need to integrate https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java#L331-L358 around `getPullRequestById`.

**Comment by tarioch** [comment]
See also #445 I think one of the fixes is very similar to what you did (basically findPr should not fetch all PRs), but I did also fix a couple of other cases, especially when reacting on webhooks

**Comment by Dohbedoh** [comment]
@tarioch right I did not notice this :(. It looks like #445 is specifically about the `BitbucketSCMSource#create` though. Whereas JENKINS-65719 is about the `BitbucketSCMSource#retrieve(SCMHead)` (Jenkinsfile retrieval) ? Let me know how you want to proceed, whether we keep two separate PRs to solve to different problem or do all at once.
One thing that we need to ensure is that the `getPullRequestById` also integrate the "callCanMerge" and "callChanges`.

**Comment by tarioch** [comment]
I would say it would be nice to be able to integrate the two things together. Both of them are actually targeting the same thing, trying to reduce the number of PRs that are fetched (which can be costly, especially with the can merge flag)

**Comment by tarioch** [comment]
I merged your changes into #445 can you please review? And if it's ok with you we can then close this PR.

**Comment by Dohbedoh** [comment]
@tarioch Yeah that looks good. Closing in favor of https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/445

**Pull request closed without merging**
