### PR TITLE
Update copy on branch discovery to not imply deprecation.

### PR DESCRIPTION
**Pull request by behoyh**
This PR updates the copy for the "Only branches that are also filed as PRs" branch discovery mode to list use cases.

### Your checklist for this pull request

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

**Comment by behoyh** [comment]
Is there a way to have specific branches toggle in this mode, (such as develop/master) and still have discovery set to PR + branch only?

**Comment by jetersen** [comment]
yes, simply add the trait for branch filter based on either wildcard or regex

**Comment by behoyh** [comment]
Should I add a note about that to the PR for user-friendliness?

**Comment by jetersen** [comment]
Those traits are coming from the scm api: https://github.com/jenkinsci/scm-api-plugin/tree/master/src/main/resources/jenkins/scm/impl/trait

**Comment by behoyh** [comment]
Oh, good. Thanks!

**Pull request merged**
