### PR TITLE
[JENKINS-43507] Remove backfill as it is available in core since Jenkins 2.50

### PR DESCRIPTION
**Pull request by darxriggs**
This removes the files added in commit 824dfd2cac7cef51da6165abfb63e574d0e550f4.
The functionality was introduced in jenkins-core via commit jenkinsci/jenkins@c3636ebf72abe18c66dc9aa906b5175e2e1de6d3.
For more details see [JENKINS-42443](https://issues.jenkins-ci.org/browse/JENKINS-42443).

### CODE REVIEW

**Comment by darxriggs** [comment]
Hi @cast, what exactly do you want to wait for?
I have seen your commit 8e01a5ea31880dac087f412e0012cbd6b14a187b, to get back to Java 7 compatibility.
I am planning to prepare another commit to get rid of `BitbucketDateFormat` by upgrading this `jackson2-api` dependency which would also require 8.

**Comment by nfalco79** [comment]
If you remove the jenkins.version property you inherit from the parent the 2.60.1 LTS version that is better than define a custom non LTS

**Comment by darxriggs** [comment]
@nfalco79, good point on suggesting to only require LTS versions.

Regarding using the `jenkins.version` as declared in the parent pom: I am of the opinion, that a plugin should explicitly declare the required minimum Jenkins version.

I'll update the required Jenkins version to v2.60.1 as this is the next LTS version after v2.50 which contains the required features. BTW, this also means that the Java level could be raised to 8.

**Comment by darxriggs** [comment]
Looks like there was a problem with the Jenkins infrastructure.

**Pull request merged**
