### PR TITLE
JENKINS-49671 Check if file exists - available for file in subdirectory

### PR DESCRIPTION
**Pull request by cyprianno**
Not to escape path separator.

BitbucketServerAPIClient uses internaly HttpClientBuilder.create() so I can't create unit tests for this change.

### CODE REVIEW

**Comment by anshprat** [comment]
Hi, is there any ETA for this to be merged?

**Comment by tarioch** [comment]
I can confirm that with this applied it works fine again with Jenkinsfiles in subdirs.

**Comment by BrunoLavitForgerock** [comment]
FYI, we have applied #117 and #111 on the master branch and the lightweight checkout is now working for our postcommit and PR pipeline jobs.

**Comment by casz** [comment]
@rsandell @amuniz @vivek PRs are piling up again :)

**Pull request merged**
