### PR TITLE
Add personal access token support

### PR DESCRIPTION
**Pull request by darxriggs**
This implements #289.

This authentication method is only available for Bitbucket Server but not for Bitbucket Cloud.

It has been introduced in Bitbucket Server 5.5:
- https://confluence.atlassian.com/bitbucketserver/bitbucket-server-5-5-release-notes-938037662.html

Documentation can be found here:
- https://confluence.atlassian.com/bitbucketserver0716/personal-access-tokens-1086402495.html

The implementation uses the Bearer ([RFC-6750](https://datatracker.ietf.org/doc/html/rfc6750)) instead of the Basic ([RFC-7617](https://datatracker.ietf.org/doc/html/rfc7617)) [HTTP authentication theme](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication). This is required to support access tokens on Bitbucket installations with disabled Basic authentication.

### CODE REVIEW

**Comment by darxriggs** [comment]
I have rebased this on the master branch to resolve the merge conflicts.

**Comment by darxriggs** [comment]
I have rebased this on the master branch to resolve the merge conflicts.

/cc @bitwiseman

**Comment by darxriggs** [comment]
@lifeofguenter Could you also take care of this PR?

**Comment by lifeofguenter** [comment]
I want to test it out first @darxriggs - but looks good otherwise :)

**Comment by darxriggs** [comment]
My manual tests locally have been as follows.

**Setup**

Credentials (globally configured)
- Secret text

Bitbucket Endpoints
- http://\<non-existent Bitbucket Server instance\>
- https://\<non-existent Bitbucket Server instance\>
- https://\<existent Bitbucket Server instance\> (enabled "Manage hooks" with a "Secret text" credential)

Jobs
- Multibranch Pipeline
- Bitbucket Team/Project

**Verifications**

- whether credentials are selectable (HTTP vs HTTPS)
- retrieving repositories from Bitbucket is working when configuring a job
- discovering branches / pull requests / tags is working
- checkout is working in a job (Checkout over SSH)
- notifying Bitbucket about the build status is working

**Comment by lifeofguenter** [comment]
Awesome stuff.. I gave it a quick test on my private installation and looks good to me :)

**Comment by darxriggs** [comment]
@lifeofguenter Many thanks.

**Pull request merged**
