### PR TITLE
Make common traits consistent with github-branch-source-plugin

### PR DESCRIPTION
**Pull request by darxriggs**
Also see https://github.com/jenkinsci/github-branch-source-plugin/pull/256.

### CODE REVIEW

**Comment by darxriggs** [comment]
hiccups on ci.jenkins.io

**Comment by casz** [comment]
@darxriggs isn't this just formatting? 🤔

**Comment by darxriggs** [comment]
It's mainly about consistent formatting but I also removed one additional `instanceof` check [here](https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/256/files#diff-df1fb18b9f83375128267f742a2adeabL64-R62).

**Comment by bitwiseman** [comment]
@darxriggs 
I love the work you're doing, thanks!  
But could you do the whitespace/formatting-only changes at least as separate commits?

**Comment by darxriggs** [comment]
I now split the original change into "formatting" and "code changes".

**Comment by darxriggs** [comment]
Is it by intention that only a squash commit instead of my individual commits made it to master?
I am asking because the commit comments get lost doing it this way.

**Comment by casz** [comment]
no they are not? They are here in the pull request? 😓

**Comment by darxriggs** [comment]
Yes they are still here (even if quite small in this case), example a6bab46288ef05a994ae080685ee86d8d6436ee5. That's really a downside of GitHub that if someone is not explicitly looking for the commit messages they are not shown very prominently.

But when having a look at a git repository's history locally one normally would not additionally consider GitHub to look for more details.

**Pull request merged**
