### PR TITLE
add missing license file based on pom.xml

### PR DESCRIPTION
**Pull request by Bkocsan**
The missing license file make it difficult to contribute from organizations with stricter contribution rules.  

### Your checklist for this pull request

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

**Review by lifeofguenter — CHANGES_REQUESTED** [review]
Thanks for this :) - I am most probably being petty, but could you please:

* remove the single-space indent
* remove the last empty line
* remove the duplicate license from the pom (as suggested by @darxriggs)

**Comment by darxriggs** [comment]
@lifeofguenter What about the license text in `pom.xml`? Should it maybe completely be removed in this PR as it would just duplicate the information in the `LICENSE.txt` file.

**Comment by KalleOlaviNiemitalo** [comment]
The comment perhaps yes -- I believe that's not distributed in hpi packages anyway.

<https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/c79f7c340cac7455b90d963bdaba9f4fb7dd2c25/pom.xml#L2-L24>

But please do not remove the `licenses` element.

<https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/c79f7c340cac7455b90d963bdaba9f4fb7dd2c25/pom.xml#L44-L49>

**Comment by KalleOlaviNiemitalo** [comment]
> update the year to "2016-" (to indicate its ongoing :D)

Because it's a CloudBees copyright notice, I feel that the years should be changed only if CloudBees say it's okay. Presumably they have internal policies on this topic.

**Comment by Bkocsan** [comment]
Thanks for the comments @lifeofguenter, @darxriggs, @KalleOlaviNiemitalo   

And please be petty. ;)

[x] remove the single-space indent
[x] remove the last empty line
[x] remove the duplicate license from the pom

**Review by lifeofguenter — APPROVED** [review]

**Pull request merged**
