### PR TITLE
Fix JENKINS-40465

### PR DESCRIPTION
**Pull request by zigarn**
[JENKINS-40465](https://issues.jenkins-ci.org/browse/JENKINS-40465)
For Bitbucket Server, use only destination repository for repository-related actions

### CODE REVIEW

**Comment by zigarn** [comment]
It's not really clean to test `BitbucketServerAPIClient` class, but I don't know what would be the preferred way in the project (add a method in `BitbucketApi` which is not really API-related?)

**Comment by i386** [comment]
WDYT @amuniz @stephenc ?

**Comment by abishek3876** [comment]
I thought this should be superseded by #53 . Didn't test this scenario though.

**Comment by stephenc** [comment]
AIUI this issue is resolved by the changes in JENKINS-43507, specifically https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/da24a3cc88a644043dfc41582b50a9cf6ce8db06/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java#L95-L102 which will be released in 2.2.0

**Comment by zigarn** [comment]
Looks like it could.
Will try it ASAP.

**Comment by i386** [comment]
@zigarn any luck?

**Comment by zigarn** [comment]
I can confirm that using the tag `cloudbees-bitbucket-branch-source-2.2.0-beta-1`, [JENKINS-40465](https://issues.jenkins-ci.org/browse/JENKINS-40465) is already solved.

**Comment by zigarn** [comment]
It's nice with all the options for managing PR. Looking forward to see this released!

**Comment by zigarn** [comment]
@i386 @stephenc : I was too quick to give my GO...
There is still a problem: the PullRequests still only store the **source** owner and repository and then try to get revisionId against it ([com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.retrieve(SCMHead, TaskListener)](https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java#L767)) but doesn't have access to other repositories than **target** owner and repository in case of a fork.
The only solution I see is to store both origin and target owner and repository info in `PullRequestSCMHead`. (But this PR is totally outdated)

**Comment by stephenc** [comment]
@zigarn, Bitbucket Server does not have this issue as we use the refs/pull-requests/N/head refspec (not without its own issues though, e.g. https://github.com/topicusfinan/bitbucket-webhooks-plugin/pull/51)

Bitbucket Cloud will work for forks in the same account (which according to Bitbucket is the majority case) but will not work for private forks to your own account as there is NO WAY WHATSOEVER to access those forks without setting the permissions when you fork, see https://bitbucket.org/site/master/issues/5814/reify-pull-requests-by-making-them-a-ref and other issues there

**Comment by zigarn** [comment]
@stephenc : no problem with the refspec, but in the code I referenced, the list of branches is checked against the source repository which may not be accessible in case of private fork.

**Comment by stephenc** [comment]
@zigarn have you looked at the new 2.2.x code?

**Comment by stephenc** [comment]
@zigarn keep in mind that we protect against such inaccessible forks during scanning, so the only time you get to the referenced method is after a full scan has discovered, and we have a guard there: https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java#L722

**Comment by zigarn** [comment]
@stephenc: In the code you're refering, `originBitbucket` is a bitbucketClient built against the currently scanned repository, so no problem to resolve the PR hash.
But when building the PR, no more reference to the target repository and the authentication problems arrived.

When testing by launching a `mvn hpi:run` on branch `master`

```
[lun. juil. 24 18:40:03 CEST 2017] Starting branch indexing...
Connecting to http://bitbucket.mycompany using user/******
Repository type: Git
Looking up PROJECT/test_jenkins_pr for branches
Checking branch local_pr from PROJECT/test_jenkins_pr
Checking branch master from PROJECT/test_jenkins_pr
      ‘Jenkinsfile’ found
    Met criteria
No changes detected: master (still at 4c553423451313f310236bb6afda201ec93f8641)

  2 branches were processed
Looking up PROJECT/test_jenkins_pr for pull requests
Checking PR-1 from PROJECT/test_jenkins_pr and branch local_pr
      ‘Jenkinsfile’ found
    Met criteria
No changes detected: PR-1 (still at f7eb292cc308ffb31145ad30c4e0e5ed7c946d51)
Checking PR-2 from ~zigarn/test_jenkins_pr and branch remote_pr
      ‘Jenkinsfile’ found
    Met criteria
No changes detected: PR-2 (still at 2175b660d8055ea35bdd391eb912f8fa7475efb1)

  2 pull requests were processed
[lun. juil. 24 18:40:23 CEST 2017] Finished branch indexing. Indexing took 19 s
Finished: SUCCESS
```

But, when building PR-2:
```
java.io.IOException: I/O error when accessing URL: /rest/api/1.0/projects/~zigarn/repos/test_jenkins_pr/branches?start=0
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getBranches(BitbucketServerAPIClient.java:378)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.retrieve(BitbucketSCMSource.java:769)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:564)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:79)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:214)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: com.cloudbees.jenkins.plugins.bitbucket.api.BitbucketRequestException: HTTP request error. Status: 401: Unauthorized.
{"errors":[{"context":null,"message":"You are not permitted to access this resource","exceptionName":"com.atlassian.bitbucket.AuthorisationException"}]}
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:516)
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getBranches(BitbucketServerAPIClient.java:363)
	... 6 more
Finished: FAILURE
```

**Comment by stephenc** [comment]
@zigarn can you create a JIRA for this new issue

**Comment by zigarn** [comment]
[JENKINS-45775](https://issues.jenkins-ci.org/browse/JENKINS-45775).
I'm trying some solutions and may come with a PR before the end of the week.

**Pull request closed without merging**
