### PR TITLE
update API_PULL_REQUEST_MERGE_PATH path for bitbucket v7

### PR DESCRIPTION
**Pull request by ltk-mpadelsky**
Based on remakes from atlassian: https://jira.atlassian.com/browse/BSERV-12284?focusedCommentId=2389584&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2389584

### Your checklist for this pull request

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Did you provide a test-case? That demonstrates feature works or fixes the issue.

This PR should use an API call to generate the correct ref for a PR through it's duration.  Change suggested by atlassian worker.

### CODE REVIEW

**Comment by jansohn** [comment]
I think the configuration option should be renamed to avoid confusions.

**Comment by jetersen** [comment]
@jansohn not sure I follow, could you provide a suggestion?
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/commenting-on-a-pull-request#adding-line-comments-to-a-pull-request

**Comment by jansohn** [comment]
@jetersen the original PR (https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/116) which introduced this API call introduced a configuration option which would not make sense anymore with the change in this PR.
So I think this PR needs to change the configuration option and description to properly reflect what it is actually doing which is auto-updating the Git refs and not checking "mergability".

**Comment by jetersen** [comment]
Well @jansohn it is a case of doing both.
When you check "mergability" than the git refs get created.
Basically it takes two to tango 😄

**Comment by jetersen** [comment]
Okay looking at the API: https://docs.atlassian.com/bitbucket-server/rest/7.1.1/bitbucket-rest.html#idp303

the API does not return the expected result of canMerge that is true.
So this PR is a hack to generate the refs.

I think we need a more complete PR for this change indeed.

**Comment by jansohn** [comment]
@jetersen but with the proposed change in this PR it does not check mergability anymore. It only calls the diff API which IMHO can also succeed even if the PR branches cannot be merged.

**Comment by jglick** [comment]
Superseded by #294 IIUC.

**Pull request closed without merging**
