### PR TITLE
JENKINS-64183 fillCredentialsIdItems fails if Amazon ECR is installed

### PR DESCRIPTION
**Pull request by PatrikSchalin**
Do not match on instances of AmazonECSRegistryCredential

### Your checklist for this pull request

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [x] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

**Comment by PatrikSchalin** [comment]
First time contribution, hope I got things in shape.

**Comment by bitwiseman** [comment]
@PatrikSchalin 
Is this a fix for #397?

**Comment by PatrikSchalin** [comment]
@bitwiseman I'm afraid not, my JS foo is not strong enough for that.

This is the fix we are using to get around: [JENKINS-64183](https://issues.jenkins.io/browse/JENKINS-64183)

**Review by bitwiseman — APPROVED** [review]
Good enough.  Thanks!

**Pull request merged**
