### PR TITLE
JENKINS-48019 : Properly close all resources of done requests

### PR DESCRIPTION
**Pull request by bguerin**

### CODE REVIEW

**Comment by marcofranssen** [comment]
When will this PR be merged? We are facing similar issues with timeouts, hopefully this PR resolves those.

**Comment by maocorte** [comment]
+1

**Comment by bguerin** [comment]
Thanks @marcofranssen @maocorte 
But to be honest, this is not enough for me, at least within my running environment ...
There are still times when my system seems stuck, looking at the stacks because of BitBucket API rate limit ..

From what I read on the Internet, https://issues.jenkins-ci.org/browse/JENKINS-48206 maybe help ... or not ... And I also think this plugin is making too much request to BitBucket API and can reduce them or at least cache some answers

**Comment by casz** [comment]
@bguerin https://github.com/jenkinsci/apache-httpcomponents-client-4-api-plugin might help :)

**Comment by challett** [comment]
+1 facing the same issue

**Comment by bguerin** [comment]
@maocorte @maocorte @challett 
Please see my full comment on JENKINS-48019 : https://issues.jenkins-ci.org/browse/JENKINS-48019?focusedCommentId=322286&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-322286

And if you want a patched plugin, you can build the master branch of our fork :
https://github.com/netceler/bitbucket-branch-source-plugin

**Comment by vivek** [comment]
LGTM. cc @stephenc @amuniz PTAL, I think its ready to be merged this.

**Comment by vivek** [comment]
@bguerin I see another PR #92 to upgrade to httpclient 4.x. That makes this PR redundant. You may want close this in favor of PR#92?

**Comment by bguerin** [comment]
You are almost right, in PR #92, I take care of almost all. But in `getRequestAsInputStream`, there is still resources consumed outside of this method, where the request is done, so we need to take care of closing properly.
Maybe I can close this one and add the fix directly into PR#92 ?

**Comment by vivek** [comment]
Sure.

**Comment by bguerin** [comment]
Closing this, superseded by #92

**Pull request closed without merging**
