### PR TITLE
[JENKINS-71355] Avoid Fetching all branches and Tags to retrieve SCM …

### PR DESCRIPTION
**Pull request by Dohbedoh**
…Head

See [JENKINS-71355](https://issues.jenkins.io/browse/JENKINS-71355). When retrieving a single SCM Head, BitbucketBranchSource currently fetches all branches (and also tags in the case of a Tag) although it is not necessary.

Note: One challenge / limitation is with Bitbucket Server API that does not have an endpoint to get a single branch information. We can however send a [filterText](https://developer.atlassian.com/server/bitbucket/rest/v810/api-group-repository/#api-api-latest-projects-projectkey-repos-repositoryslug-branches-get) parameter to get what we want and then use a predicate to make sure we have the correct branch (because per my understanding the filter may returns several matches if for example a branch name is a substring of another one). But in most cases, just the branch we look for will be returned.

### Your checklist for this pull request

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

**Comment by Dohbedoh** [comment]
I have run tests against Bitbucket Server branches, tags and PR from origin.
I have not run tests against Bitbucket Cloud yet or PR from forks.

**Comment by Dohbedoh** [comment]
Failing in Bitbucket Cloud because the `/2.0/repositories/{owner}/{repo}/pullrequests/{id}` returns short commit ID instead of long ones. That eventually causes the `AbstractGitSCMSource` to fail when using jgit https://github.com/jenkinsci/git-plugin/blob/git-5.0.2/src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java#L1479:

```
org.eclipse.jgit.errors.InvalidObjectIdException: Invalid id: 620d3c2bc24e
	at org.eclipse.jgit.lib.ObjectId.fromString(ObjectId.java:203)
	at jenkins.plugins.git.AbstractGitSCMSource$SpecificRevisionBuildChooser.<init>(AbstractGitSCMSource.java:1479)
	at jenkins.plugins.git.GitSCMBuilder.build(GitSCMBuilder.java:504)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketGitSCMBuilder.build(BitbucketGitSCMBuilder.java:291)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.build(BitbucketSCMSource.java:1027)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:137)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:312)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)
```

Seems like this is a known problem but that in the context the PR commits are never initialized (we never go through the [BitbucketCloudBranch#initHeadCommitInfo](https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/800.va_b_b_9a_a_5035c1/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/branch/BitbucketCloudBranch.java#L130-L147)) method. Called lazily when retrieving information about the PR (`getAuthor`, `getDateMillis`, `getMessage`). We need to force this in this context.

**Comment by lifeofguenter** [comment]
Thanks @Dohbedoh for this (and also providing tests), I will merge in shortly

**Comment by Dohbedoh** [comment]
@lifeofguenter wait, see my previous comment. I need to adjust this to get the commit IDs from branches in case of Bitbucket Cloud. Will commit shortly.

**Comment by Dohbedoh** [comment]
@lifeofguenter ready for review

**Comment by chwehrli** [comment]
When upgrading this plugin from v803 to v804 multibranch pipeline jobs "don't run" anymore. I can trigger the job but it gets stuck at the very beginning (there's literally no job log) and eventually times out after a couple of minutes. If I kill the job I get the following log:

`
07:31:45  Started by user Wehrli, Christian
07:32:21  java.lang.InterruptedException
07:32:21  	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getResource(BitbucketServerAPIClient.java:917)
07:32:21  	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getSingleBranch(BitbucketServerAPIClient.java:639)
07:32:21  	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getBranch(BitbucketServerAPIClient.java:590)
07:32:21  	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getBranch(BitbucketServerAPIClient.java:130)
07:32:21  	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.retrieve(BitbucketSCMSource.java:912)
07:32:21  	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:581)
07:32:21  	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:99)
07:32:21  	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:312)
07:32:21  	at hudson.model.ResourceController.execute(ResourceController.java:101)
07:32:21  	at hudson.model.Executor.run(Executor.java:442)
07:32:21  [withMaven] downstreamPipelineTriggerRunListener - Failure to introspect build steps: java.io.IOException: Core Performance ZKB Cluster/master #948 did not yet start
07:32:21  [withMaven] downstreamPipelineTriggerRunListener - Failure to introspect build steps: java.io.IOException: Core Performance ZKB Cluster/master #948 did not yet start
07:32:21  Finished: FAILURE
`

Jenkins LTS 2.401.1

Any idea what's going on here?  Happy to provide additional information or to raise a bug.

**Pull request merged**
