### PR TITLE
Fix JENKINS-56322 - local domain validation (bitbucket server)

### PR DESCRIPTION
**Pull request by fonsecas72**

### CODE REVIEW

**Comment by casz** [comment]
this is required for bitbucket cloud @fonsecas72 so 🤷‍♂️

**Comment by michelzanini** [comment]
To me it does not make sense to support `http://localhost`... This URL will be used on links on Bitbucket, which will point to localhost which does not make too much sense.

**Comment by michelzanini** [comment]
The version I created only checked this:

```
if (url.startsWith("http://localhost")) {
            throw new IllegalStateException("Jenkins URL cannot start with http://localhost");
 }
```

After it was changed to check the . (dot)... Dot would work for localhost. If we are removing the . (dot) can we add back a check for localhost being forbidden?

**Comment by casz** [comment]
@MrCitron please take a look, you were the last to modify it :)

**Comment by fonsecas72** [comment]
@casz  The version we are using is v5.13.1. Can you point me to the documentation where you saw that using a valid fqdn is a requirement? 
From my point of view, bitbucket server and jenkins are tools that should work perfectly on local networks, even in a single machine with no internet access if needed, so requiring a valid fqdn sounds odd.

**Comment by MrCitron** [comment]
@casz My original issue was that my local jenkins server was not able to give it local address to bitbucket cloud, as BB cloud is expecting a fqdn or an IP (if I remember well)

Seems like @fonsecas72 has another issue with BB server flavor. If this PR is merged as is, my original issue will come back again.

IMO there should be a test regarding the flavor of BB (server or cloud) and making decision on the validity of the Jenkins URL based on this.

**Pull request merged**
