### PR TITLE
[JENKINS-59553] - Automatic hook registration use different scoped REST path on update

### PR DESCRIPTION
**Pull request by nfalco79**
The cloud api client to retrieve the list of web hooks and register new ones uses REST path specific for repository instead to update use the team REST API path. Other details are in the Jira issue.

### Your checklist for this pull request

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Did you provide a test-case? That demonstrates feature works or fixes the issue.

@casz tomorrow let add a test case to cover the cloud client for web hook update

### CODE REVIEW

**Comment by casz** [comment]
Not sure why your branch is foobar on Jenkins CI

**Comment by nfalco79** [comment]
@casz a test case has been added.
About the changes of getRequest visibility in the BitbucketCloudApiClient initially was changed fro private to protected by me in a previous PR to make cloud client testable. Now I had revert the visibility to private because I need to use a more generic method doRequest (to cover also PUT and POST).

**Comment by casz** [comment]
Codacy is after you @nfalco79

**Comment by nfalco79** [comment]
Yes but:
* the json must be empty because the response has not content (I can not change)
* the interface is for test purpose and used only internally in the integration factory (has not much sense)
* test method is not the only one that has that naming convention (I will rename but really sad)

The only reasonable is:
- Unnecessary use of fully qualified name 'Mockito.mock' due to existing static import 'org.mockito.Mockito.mock'

**Comment by nfalco79** [comment]
@casz done all are green (the Codacy issue is a false positive)

**Comment by nfalco79** [comment]
@casz Do you have any other change request?

**Comment by casz** [comment]
😅 Forgot all about this PR, thanks for poking.

I wonder if you would like maintainer / release permission? :)

**Comment by casz** [comment]
Fair enough 😆

**Pull request merged**
