### PR TITLE
[JENKINS-38748] Add auto register for BB server

### PR DESCRIPTION
**Pull request by Eernie**
[JENKINS-38748](https://issues.jenkins-ci.org/browse/JENKINS-38748)

This works together with 
PR https://github.com/topicusfinan/bitbucket-webhooks-plugin/pull/7 
@amuniz @reviewbybees

### CODE REVIEW

**Comment by amuniz** [comment]
Cool! I hope to find some time to review it soon. Thanks.

**Comment by tiny-dancer** [comment]
Any update?

**Comment by stephenc** [comment]
Will need changes to mesh with the changes to scm-API that I'm in the process of pushing through

**Comment by olbrichj** [comment]
Any update on this one?

**Comment by Eernie** [comment]
I'm waiting for PR #23 to be merged, then I'll rebase this branch.

**Comment by anderius** [comment]
@Eernie: PR #23 seems to be merged now! :-)

**Comment by olbrichj** [comment]
any update?

**Comment by Eernie** [comment]
@amuniz @stephenc This is open for review again :)

**Comment by casz** [comment]
Bummer conflicts due to #35 they seem simple but BitbucketServerAPIClient has quite a few conflicts, was looking forward to this PR 👍

**Comment by sean-brandt** [comment]
Any progress here?

**Comment by Eernie** [comment]
Will try to fix these conflicts this weekend.

**Comment by casz** [comment]
🎉 Party time 🎉

**Pull request merged**
