### PR TITLE
Only add FirstCheckoutCompletedInvisibleAction if this build is using BitbucketSCMSource

### PR DESCRIPTION
**Pull request by jglick**
Experimentation with a plugin usage tool looking for `Run.actions` found that this plugin was attaching its action to every build even when Bitbucket was not in use. Corrects a regression in #130 by @michelzanini.

### Your checklist for this pull request

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [ ] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

**Comment by bitwiseman** [comment]
@jglick 
Okay, I look forward to tests being written.

**Comment by jglick** [comment]
#130 was merged without tests. I do not intend to retroactively test that; I _should_ be able to verify the effectiveness of this amendment however.

**Comment by jglick** [comment]
@bitwiseman do you plan to fix the new compilation error or shall I?

**Comment by bitwiseman** [comment]
@jglick  I'll get it.

**Pull request merged**
