### PR TITLE
[JENKINS-62669] Removing Mercurial support

### PR DESCRIPTION
**Pull request by jglick**
See [JENKINS-62669](https://issues.jenkins-ci.org/browse/JENKINS-62669) for discussion.

- [X] checked for references to these types for other plugins

### CODE REVIEW

**Comment by jglick** [comment]
EC2 outage.

**Comment by jglick** [comment]
An `OldDataMonitor` warning seems possible, if you happened to be loading some old builds. I am not particularly inclined to treat that as a problem.

**Comment by jglick** [comment]
> Some stuff like `BitbucketRepositoryType` is totally pointless now

Yes, and I have tried to mark that stuff as deprecated. I would not mind actually removing it here, but I am not totally confident in the test coverage, and there is magical JSON mapping that would result in only runtime errors if something actually turned out to be needed.

**Comment by dwnusbaum** [comment]
Based on https://bitbucket.org/blog/sunsetting-mercurial-support-in-bitbucket, Mercurial support has been gone since August 2020, so I am going to merge and release this.

**Comment by jglick** [comment]
I also have a BB account on which I used to have a couple dozen Hg repos. The interesting ones I already converted to Git and moved to GH; the remaining ones seem to have vanished from the UI. So AFAICT it is dead dead.

**Pull request merged**
