### PR TITLE
Avoid double String.format()

### PR DESCRIPTION
**Pull request by stephenc**
Reported on https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/78#issuecomment-343090109

### CODE REVIEW

**Comment by stephenc** [comment]
@vivek @casz

**Comment by vivek** [comment]
Ouch! Thanks @stephenc @casz!

**Comment by michaelneale** [comment]
ah - is this the one reported in: https://issues.jenkins-ci.org/browse/JENKINS-42518?focusedCommentId=319278&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-319278 ?

**Comment by michaelneale** [comment]
yes it is

sorry very late but great catch

**Pull request merged**
