### PR TITLE
JENKINS-45891 - fix 'cannot resolve upstream (mixed local/remote)'

### PR DESCRIPTION
**Pull request by jmguilla**
Hello guys!

This is a fix for https://issues.jenkins-ci.org/browse/JENKINS-45891
I have implemented the fix suggested by [Sven here](https://issues.jenkins-ci.org/browse/JENKINS-45891?focusedCommentId=313514&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-313514) and it seems it work.

Thx

### CODE REVIEW

**Comment by jmguilla** [comment]
Hi guys!

Many of our clients are stuck with this problem. Is it possible to have some feedback?
Thank you very much!

All my best

**Comment by coliva** [comment]
Hello,

This fix is really needed as it is a pain for now to not be able to have pull requests from master to master.

Any idea when this will be integrated?

Cheers

**Comment by slamp** [comment]
+1

**Comment by casz** [comment]
@amuniz @stephenc sorry for pinging just wanted a make sure people were heard, also the 👍 are silent but there.

Could we get an update?

**Comment by jhull123** [comment]
This is an important fix! Please merge!!

**Comment by krusolu** [comment]
+1

**Comment by jeffsigmon** [comment]
+1

**Comment by Ramakrishna-Mandepudi** [comment]
+1

**Comment by casz** [comment]
@rsandell Could we have an update on this PR status?

**Comment by Guillaumichaud** [comment]
+1

**Comment by casz** [comment]
@stephenc facepalm does not load properly 😭

**Pull request merged**
