### PR TITLE
fix: call the /changes API to make the commit hash available in the target repo

### PR DESCRIPTION
**Pull request by sjjarvi**
## Description

Proposed fix for the problem raised in [ issue #469](https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/469) regarding fork-based PRs not triggering builds.  In order for a commit hash from a fork-based PR to be made visible in the target repo, a call to the `/changes` API must be made.  The fix was based on comments found in [BitbucketServerAPIClient.setupPullRequest()](https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java#L338-L362) which were discussed with and confirmed by Atlassian support.

### Testing

A new unit test has been provided that exercises code paths within `BitbucketSCMSource.retrieve(SCMSourceCriteria, SCMHeadObserver observer, SCMHeadEvent, TaskListener)`.  As this method is void, the test attempts to verify its side effects, namely specific API calls that are made by the client.

#### Manual Testing

This change has been tested using Bitbucket Server v7.6.7 with native webhooks and Jenkins 2.319.1. We've been running with this fix on our production Jenkins instances for about two weeks and have not noticed any problems.  
Test scenarios include:
* Open new fork-based PR
* Push new commits to fork-based PR (including rebase and force push)
* Decline and re-open fork-based PR
* Open new feature branch-based PR
* Push new commits to feature branch-based (including rebase and force push)
* Decline and re-open feature branch-based PR
As the issue for us was primarily with fork-based PRs, the testing against feature branches was for regression purposes.

## 04-15-2022 Update on Bitbucket Cloud Testing
I was able able to create an environment that allowed me to test this change against Bitbucket Cloud
* Jenkins version: `2.332.2`
* Plugin version : `762.v969cfe087fc0` + my changes

Testing summary below:

#### Fork-based PR Created

```
[Fri Apr 15 14:45:03 UTC 2022] Received com.cloudbees.jenkins.plugins.bitbucket.hooks.PullRequestHookProcessor$HeadEvent CREATED event from 18.246.31.227 ⇒ http://my-jenkins-host/bitbucket-scmsource-hook/notify with timestamp Fri Apr 15 14:44:58 UTC 2022
Connecting to https://bitbucket.org using scott_jarvi/******
Repository type: Git
Looking up scott_jarvi/bb-branch-source-plugin for branches
Checking branch feature/doc-updates from scott_jarvi/bb-branch-source-plugin
Checking branch main from scott_jarvi/bb-branch-source-plugin

  2 branches were processed
Looking up scott_jarvi/bb-branch-source-plugin for pull requests
Checking PR-4 from scott_jarvi/bb-branch-source-plugin-fork and branch feature/refactor-docs
      ‘Jenkinsfile’ found
    Met criteria
Scheduled build for branch: PR-4
```

#### Fork-based PR Updated

```
[Fri Apr 15 14:52:26 UTC 2022] Received com.cloudbees.jenkins.plugins.bitbucket.hooks.PullRequestHookProcessor$HeadEvent UPDATED event from 18.246.31.232 ⇒ http://my-jenkins-host/bitbucket-scmsource-hook/notify with timestamp Fri Apr 15 14:52:21 UTC 2022
Connecting to https://bitbucket.org using scott_jarvi/******
Repository type: Git
Looking up scott_jarvi/bb-branch-source-plugin for branches
Checking branch feature/doc-updates from scott_jarvi/bb-branch-source-plugin
Checking branch main from scott_jarvi/bb-branch-source-plugin

  2 branches were processed
Looking up scott_jarvi/bb-branch-source-plugin for pull requests
Checking PR-4 from scott_jarvi/bb-branch-source-plugin-fork and branch feature/refactor-docs
      ‘Jenkinsfile’ found
    Met criteria
Changes detected: PR-4 (a2600ebcc065+6eb6736cba2a → b7e50a0d9281+6eb6736cba2a)
Scheduled build for branch: PR-4
```

#### Fork-based PR Declined

```
[Fri Apr 15 14:56:24 UTC 2022] Received com.cloudbees.jenkins.plugins.bitbucket.hooks.PullRequestHookProcessor$HeadEvent REMOVED event from 18.246.31.227 ⇒ http://my-jenkins-host/bitbucket-scmsource-hook/notify with timestamp Fri Apr 15 14:56:19 UTC 2022
Connecting to https://bitbucket.org using scott_jarvi/******
Repository type: Git
Looking up scott_jarvi/bb-branch-source-plugin for branches
Checking branch feature/doc-updates from scott_jarvi/bb-branch-source-plugin
Checking branch main from scott_jarvi/bb-branch-source-plugin

  2 branches were processed
Looking up scott_jarvi/bb-branch-source-plugin for pull requests

  0 pull requests were processed
  ```

#### Fork-based PR Created

```
[Fri Apr 15 01:38:34 UTC 2022] com.cloudbees.jenkins.plugins.bitbucket.hooks.PullRequestHookProcessor$HeadEvent CREATED event from 18.246.31.227 ⇒ http://my-jenkins-host/bitbucket-scmsource-hook/notify with timestamp Fri Apr 15 01:38:28 UTC 2022 processed in 0.53 sec
[Fri Apr 15 13:06:37 UTC 2022] Received com.cloudbees.jenkins.plugins.bitbucket.hooks.PullRequestHookProcessor$HeadEvent CREATED event from 18.246.31.224 ⇒ http://my-jenkins-host/bitbucket-scmsource-hook/notify with timestamp Fri Apr 15 13:06:31 UTC 2022
Connecting to https://bitbucket.org using scott_jarvi/******
Repository type: Git
Looking up scott_jarvi/bb-branch-source-plugin for branches
Checking branch feature/doc-updates from scott_jarvi/bb-branch-source-plugin
Checking branch main from scott_jarvi/bb-branch-source-plugin

  2 branches were processed
Looking up scott_jarvi/bb-branch-source-plugin for pull requests
Initialized PR: https://bitbucket.org/scott_jarvi/bb-branch-source-plugin/pull-requests/3
Checking PR-3 from scott_jarvi/bb-branch-source-plugin-fork and branch feature/more-doc-updates
      ‘Jenkinsfile’ found
    Met criteria
Scheduled build for branch: PR-3
```

#### Fork-based PR Updated

```
[Fri Apr 15 14:01:15 UTC 2022] Received com.cloudbees.jenkins.plugins.bitbucket.hooks.PullRequestHookProcessor$HeadEvent UPDATED event from 18.246.31.231 ⇒ http://my-jenkins-host/bitbucket-scmsource-hook/notify with timestamp Fri Apr 15 14:01:10 UTC 2022
Connecting to https://bitbucket.org using scott_jarvi/******
Repository type: Git
Looking up scott_jarvi/bb-branch-source-plugin for branches
Checking branch feature/doc-updates from scott_jarvi/bb-branch-source-plugin
Checking branch main from scott_jarvi/bb-branch-source-plugin

  2 branches were processed
Looking up scott_jarvi/bb-branch-source-plugin for pull requests
Initialized PR: https://bitbucket.org/scott_jarvi/bb-branch-source-plugin/pull-requests/3
Checking PR-3 from scott_jarvi/bb-branch-source-plugin-fork and branch feature/more-doc-updates
      ‘Jenkinsfile’ found
    Met criteria
Changes detected: PR-3 (36e988c88ba5+6eb6736cba2a → 283f5098f707+6eb6736cba2a)
Scheduled build for branch: PR-3
```

#### Fork-based PR Declined

```
[Fri Apr 15 14:10:42 UTC 2022] Received com.cloudbees.jenkins.plugins.bitbucket.hooks.PullRequestHookProcessor$HeadEvent REMOVED event from 18.246.31.232 ⇒ http://my-jenkins-host/bitbucket-scmsource-hook/notify with timestamp Fri Apr 15 14:10:37 UTC 2022
Connecting to https://bitbucket.org using scott_jarvi/******
Repository type: Git
Looking up scott_jarvi/bb-branch-source-plugin for branches
Checking branch feature/doc-updates from scott_jarvi/bb-branch-source-plugin
Checking branch main from scott_jarvi/bb-branch-source-plugin

  2 branches were processed
Looking up scott_jarvi/bb-branch-source-plugin for pull requests
```

While this issue does not impact feature branches from the main repo, I ran the same test scenarios using feature branches and found no issues.

### Your checklist for this pull request

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

**Comment by lifeofguenter** [comment]
Awesome, thanks for this <3

Will this have to he tested against bitbucket cloud as well?

**Comment by sjjarvi** [comment]
@lifeofguenter I have not tested this against bitbucket cloud, but I would think that should be part of regression testing.   Also, I kept this in draft mode since I'm still looking for a way to get some unit (or integration) test coverage against my changes.  I'm fairly new to this codebase so any advice you have is welcome :)

**Comment by sjjarvi** [comment]
@lifeofguenter Since this fix is meant for #469 which is labeled as a `bug`, should this PR also be labeled as a `bug` vs. `enhancement`?

**Comment by lifeofguenter** [comment]
Thanks @sjjarvi - would be great to have some tests for this. The reason being (and we just recent had an issue around that), we are currently supporting three different APIs:

* Bitbucket Cloud
* Bitbucket Server Plugin
* Bitbucket Server Native

So this fix might work for one, but not for all.

Ideally though I would like to get rid of the plugin code at some point so we can funnel efforts towards Cloud and Native.

I am adding this as enhancement (for now) because I am [unable to replicate a general issue with PRs/forks for now](https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/521#issuecomment-1029450530).

**Comment by sjjarvi** [comment]
@lifeofguenter I added a test to exercise the class/method that was changed.  I welcome your feedback.

Regarding manual testing against Bitbucket cloud - due to constraints in our testing environment it is not feasible to set up that scenario.   Is there a test environment that you use for this project that I could get access to for testing?

**Review by car-roll — APPROVED** [review]
LGTM, definitely appreciate the additional testing for cloud

**Review by jtnord — APPROVED** [review]
Seems ok.  I am a little concerned that the code is going to make more API calls (one extra for every PR rather than just one for all) and potentially hit the rate limit much sooner, but deferring the request until it fails (and then retrying after making a call) would appear to be much less cleaner.

**Comment by lifeofguenter** [comment]
my only worry is if this will break bitbucket cloud :)

**Comment by sjjarvi** [comment]
> my only worry is if this will break bitbucket cloud :)

@lifeofguenter I was able to get test environment for BB Cloud and have updated the PR description with my test results.

**Pull request merged**
